### ISSUE TITLE
Feat. admin 기능 구현

### ISSUE THREAD

**Issue by junstory** [junstory/24-2FullstackServiceProgramming#10]
## Description
admin Role인지 확인 해야 함.

기능은 아래와 같음.
- 입사 신청한 사용자 인증(company의 is_activated를 on)
- 회사에서 사용자 제거(company의 is_activated를 off)
- 사용자의 출/퇴근 시간 수정
- 사용자 출/퇴근 기록 확인

## Todo
- [x] 사용자를 회사에 등록 
- [x] 회사에서 삭제
- [x] 출근 시간 수정
- [x] 퇴근 시간 수정
- [ ] 출/퇴근 기록 확인(월 단위로, 존재하지 않는 데이터는 보여주지 않음.)
